default_language_version:
  python: python3.14
default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
  - repo: https://github.com/enabletechnologies/pre-commit-hooks
    rev: v26.1.2
    hooks:
      - id: commitizen
      - id: lint
      - id: check_uv_toml
      - id: check_commit_msg
      - id: check_branch_name
