default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
  - repo: https://github.com/enabletechnologies/pre-commit-hooks
    rev: v25.8.1
    hooks:
      - id: commitizen
        language_version: python3.13
      - id: lint
        language_version: python3.13
      - id: check_uv_toml
        language_version: python3.13
      - id: check_commit_msg
        language_version: python3.13
